openapi: 3.0.1
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: '0.1'
servers:
  - url: /
paths:
  /lottery/{id}:
    get:
      summary: retrieve the lottery row of the specified user
      tags: [ Lottery ]
      operationId: mib.resources.lottery.retrieve_by_id
      parameters:
        - name: id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        200:
          description: Retrieve the user
        404:
          description: User not found
        default:
          description: Error while getting the user
    post:
      summary: create a new lottery row for the specified user
      tags: [ Lottery ]
      operationId: mib.resources.lottery.lottery_create_user
      parameters:
        - name: id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        201:
          description: User created
        default:
          description: Error while creating the user