"""empty message

Revision ID: 6012c060ecb5
Revises: 
Create Date: 2021-12-03 10:09:33.211887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6012c060ecb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lottery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lottery')
    # ### end Alembic commands ###
